In [ ]:
%pip install numpy

In [3]:
import numpy as np

In [4]:
a1D = np.array([1,2,3])
a1D

array([1, 2, 3])

In [5]:
type(a1D)

numpy.ndarray

In [7]:
a1D.dtype

dtype('int64')

In [8]:
b1D = np.array([1,2,3], dtype = float)
b1D

array([1., 2., 3.])

In [9]:
b1D.dtype

dtype('float64')

In [10]:
c1D = np.array([1,2,3], dtype = str)
c1D

array(['1', '2', '3'], dtype='<U1')

In [ ]:
# str > float > int > bool (nesse caso, todos os elementos são salvos como string, por conta da precedencia entre os tipo)
d1D = np.array([1, 3.14, "NumPy", True])
d1D

array(['1', '3.14', 'NumPy', 'True'], dtype='<U32')

In [12]:
# Array de duas dimensões (Matriz)
a2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
a2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
azeros = np.zeros(5)
azeros

array([0., 0., 0., 0., 0.])

In [15]:
aones = np.ones((5, 4))
aones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
array_listado = np.arange(10,30,2)
array_listado

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [19]:
array_igualmente = np.linspace(10, 30, 3)
array_igualmente

array([10., 20., 30.])

In [20]:
array_igualmente2 = np.linspace(10, 30, 3, dtype = int)
array_igualmente2

array([10, 20, 30])

In [21]:
array_igualmente3 = np.linspace(10, 30, 3, dtype = int, endpoint=False)
array_igualmente3

array([10, 16, 23])

In [22]:
array_full = np.full(10, 5)
array_full

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [23]:
array_full2 = np.full((10, 5), -1)
array_full2

array([[-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

In [25]:
ident = np.eye(5)
ident

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
aleatorio = np.random.randint(0,100, 10)
aleatorio

array([73, 55, 33,  5, 34, 63, 72, 59, 89, 75], dtype=int32)

In [27]:
aleatorio2 = np.random.randint(0,100, (4,5))
aleatorio2 

array([[ 0, 46, 38,  5,  0],
       [15, 91, 52, 43, 51],
       [ 2, 50, 68, 97, 22],
       [17, 47,  3, 74,  9]], dtype=int32)

In [30]:
aleatorio3 = np.random.randint(1,61, (10,1,6))
aleatorio3 

array([[[14, 11,  5, 52,  5, 47]],

       [[59, 17, 43, 10, 21, 37]],

       [[ 3,  2, 52, 59, 17, 38]],

       [[10, 12, 10, 22, 13, 43]],

       [[48, 44, 19, 38,  3, 53]],

       [[52, 43, 16, 48, 38, 52]],

       [[ 4, 49,  1, 60, 34,  1]],

       [[26, 38, 41, 16, 25, 37]],

       [[29, 47, 24,  4, 59, 15]],

       [[ 2, 27, 22, 18, 17, 32]]], dtype=int32)

In [29]:
aleat = np.random.random(10)
aleat

array([0.46601192, 0.97014992, 0.37944636, 0.62203212, 0.20884593,
       0.22537803, 0.72943624, 0.61527365, 0.73943431, 0.49295675])

In [31]:
aleat2 = np.random.random((10, 2))
aleat2

array([[0.36355644, 0.81594879],
       [0.93918732, 0.12948018],
       [0.05449818, 0.29199613],
       [0.01288956, 0.68975557],
       [0.17361596, 0.26097214],
       [0.98659485, 0.10807833],
       [0.72275975, 0.87327516],
       [0.57715604, 0.42804263],
       [0.82838767, 0.95639919],
       [0.29052133, 0.33255344]])

##### As colunas tem axis = 0 e as linhas axis = 1 (0 corresponde ao eixo y e o 1 corresponde ao eixo x)